name: Build Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: '5.4' # Or the version compatible with your build.lua

      - name: Run build script
        run: lua build.lua