name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: '5.4' # Or the version compatible with your build.lua

      - name: Run build script
        run: lua build.lua

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
